// Snapshot adapted from CryptoAgg public product data on 2026-04-27.
// Source bundle: https://crypto-card-aggregator.vercel.app/assets/index-CS-GyK4t.js
// Verify live issuer terms, regions, fees, and rewards before commercial use.
window.CARD_DATA = [
  {
    "id": "nexo-card",
    "rank": 1,
    "name": "Nexo Card",
    "issuer": "Nexo",
    "type": "Credit",
    "network": "Mastercard",
    "cashbackMax": 2,
    "annualFee": "Free",
    "fxFee": "0.2%-2.5%",
    "signupBonus": "$25 BTC",
    "custody": "Custodial",
    "regions": "EEA, UK",
    "officialLink": "https://nexo.com/crypto-card",
    "metal": true,
    "stakingRequired": "None (Portfolio-based)",
    "atmLimit": "€2,000/mo free (Platinum)",
    "mobilePay": true,
    "supportedAssets": "60+ Assets",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "GBP",
      "USD"
    ],
    "perks": [
      "up to 2% crypto cashback",
      "earn up to 14% interest per year on unspent balance, paid out daily",
      "use worldwide at over 100 million merchants",
      "up to €2,000 / £1,800 free ATM withdrawals per month (Platinum tier)",
      "Apple Pay and Google Pay supported",
      "no monthly, annual, or inactivity card fees"
    ]
  },
  {
    "id": "coinbase-card",
    "rank": 2,
    "name": "Coinbase Card",
    "issuer": "Coinbase",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 4,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "US (except Hawaii)",
    "officialLink": "https://www.coinbase.com/card",
    "status": "active",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.coinbase.com/card",
    "availabilityNote": "US customers only, excluding Hawaii.",
    "cardForm": "Virtual + physical",
    "cryptoRole": "Spend cash or crypto; crypto rewards",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Spend limits apply",
    "mobilePay": true,
    "supportedAssets": "All Coinbase Assets",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Earn crypto without buying crypto",
      "No hidden fees",
      "Industry-leading security features (2FA, card freezing, PIN change, etc.)",
      "Switch rewards at any time",
      "Fund with bank account or paycheck (zero fees)",
      "No credit check",
      "24/7 support"
    ]
  },
  {
    "id": "okx-card",
    "rank": 2.5,
    "name": "OKX Card",
    "issuer": "OKX",
    "type": "Debit",
    "network": "Visa/Mastercard",
    "cashbackMax": 10,
    "annualFee": "Free",
    "fxFee": "0% issuer FX fee; market spread may apply",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "EEA and eligible OKX Pay regions",
    "officialLink": "https://my.okx.com/en-eu/pay",
    "status": "active",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.okx.com/en-us/help/whats-okx-card",
    "availabilityNote": "Virtual card only; availability depends on OKX Pay eligibility and region.",
    "cardForm": "Virtual",
    "cryptoRole": "Stablecoin spend",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Not specified",
    "mobilePay": true,
    "supportedAssets": "USDC, USDG and eligible OKX Pay balances",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR"
    ],
    "perks": [
      "Pay with stablecoins anywhere Mastercard is accepted in eligible regions",
      "Virtual card available in the OKX app",
      "Apple Pay and Google Pay supported",
      "No OKX transaction or FX fee; spread may apply",
      "Cashback on eligible purchases"
    ]
  },
  {
    "id": "binance-card",
    "rank": 3,
    "name": "Binance Card",
    "issuer": "Binance",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 3,
    "annualFee": "Free",
    "fxFee": "1-2%",
    "signupBonus": "$100",
    "custody": "Custodial",
    "regions": "Brazil and eligible LATAM markets",
    "officialLink": "https://www.binance.com/en/cards",
    "status": "active",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.binance.com/en/support/faq/detail/53e464e091ba40d39f88f5f62882166c",
    "availabilityNote": "Current official coverage is limited; Brazil is explicitly documented.",
    "cardForm": "Virtual",
    "cryptoRole": "Spend crypto",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "3,000 BRL/day",
    "mobilePay": true,
    "supportedAssets": "USDT, USDC, FDUSD, BNB, BTC, ETH, SOL, ADA, LINK, XRP",
    "kyc": "Required",
    "supportedCurrencies": [
      "BRL",
      "ARS",
      "COP"
    ],
    "perks": [
      "Earn up to 3% cashback on every purchase",
      "Earn up to 250 BRL/month",
      "Automatic cashback that deposits into your account every month",
      "Increased Cashback for all spending in Dec 2025 - Feb 2026",
      "Spend with Virtual Card Immediately After Applying",
      "Pay anywhere, anytime with crypto"
    ]
  },
  {
    "id": "Kripicard",
    "rank": 4,
    "name": "Premium",
    "issuer": "Kripicard",
    "type": "Credit",
    "network": "Visa",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "Zero FX fees",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "Global",
    "officialLink": "https://kripicard.com/register/Param25",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "NA",
    "mobilePay": true,
    "supportedAssets": "Bitcoin, ETH, USDT, XMR, LTC, TON , ETH, SOL , BNB , DOGE , TRON ",
    "kyc": "None",
    "supportedCurrencies": [
      "USD",
      "HKD"
    ],
    "perks": [
      "0% Cashback",
      "0% FX fees",
      "Virtual card",
      "Google Pay",
      "Apple Pay ",
      "Paypal "
    ]
  },
  {
    "id": "cdc-visa",
    "rank": 5,
    "name": "Crypto.com Visa",
    "issuer": "Crypto.com",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 8,
    "annualFee": "Staking",
    "fxFee": "ATM withdrawal fees, interbank exchange rates, top-up fees, and other charges may apply depending on your jurisdiction and card tier",
    "signupBonus": "$25 CRO",
    "custody": "Custodial",
    "regions": "Global (US, EU, UK, CA, APAC)",
    "officialLink": "https://crypto.com/en/cards",
    "metal": true,
    "stakingRequired": "Yes ($500-$1,000,000 CRO)",
    "atmLimit": "$200-$1,000/mo free (tier-dependent)",
    "mobilePay": true,
    "supportedAssets": "Fiat/CRO",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR",
      "GBP",
      "CAD",
      "SGD",
      "AUD"
    ],
    "perks": [
      "CRO Rewards on everyday spending (0% to 8% depending on tier)",
      "CRO Rewards on travel spending (up to 1.5% to 15% depending on tier, coming soon)",
      "Priority support (from Ruby Steel tier)",
      "Voice & messaging support (from Jade Green / Royal Indigo tier)",
      "Exclusive experiences: F1, UFC, UEFA & more (from Jade Green / Royal Indigo tier)",
      "Private account manager (coming soon from Jade Green / Royal Indigo tier)",
      "Subscription rebates: Spotify, Netflix, and Truth+ (3 months to permanent depending on tier)",
      "Airport lounge access (from Jade Green / Royal Indigo tier, with variations by tier)"
    ]
  },
  {
    "id": "bybit-card",
    "rank": 6,
    "name": "Bybit Card",
    "issuer": "Bybit",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 10,
    "annualFee": "Free",
    "fxFee": "0.5%",
    "signupBonus": "20 USDT",
    "custody": "Custodial",
    "regions": "Argentina, AIFC, Georgia, Kazakhstan, Australia, Mexico, Brazil, Peru, Asia Pacific (EEA excluded)",
    "officialLink": "https://www.bybit.com/en/cards",
    "status": "active",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.bybit.com/en/help-center/article/FAQ-Bybit-Card-General-Inquiries",
    "availabilityNote": "Bybit states the card is not meant for EEA customers; supported card type and network vary by region.",
    "cardForm": "Virtual + physical where available",
    "cryptoRole": "Spend crypto",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "100 USD/mo free",
    "mobilePay": true,
    "supportedAssets": "8+ Cryptos",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "USD",
      "GBP"
    ],
    "perks": [
      "10% cashback up to 150 USD for selected users",
      "100% rebates on selected partners",
      "2% to 10% cashback rewards on everyday spending",
      "Compatible with Apple Pay, Google Pay, and Samsung Pay",
      "Earn up to 8% APR on idle funds with Auto-Earn",
      "Free worldwide delivery"
    ]
  },
  {
    "id": "kast-card",
    "rank": 7,
    "name": "KAST Card",
    "issuer": "KAST",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 8,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "NFT",
    "custody": "Non-Custodial",
    "regions": "Global (160+ countries)",
    "officialLink": "https://www.kast.xyz/",
    "metal": false,
    "stakingRequired": "Yes (earn points boost on staked SOL)",
    "atmLimit": "Varies by Region",
    "mobilePay": true,
    "supportedAssets": "USDC, SOL, ETH, BTC",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR",
      "Global"
    ],
    "perks": [
      "Rewards points",
      "Instant access",
      "Points boost",
      "VIP Concierge"
    ]
  },
  {
    "id": "gemini-card",
    "rank": 8,
    "name": "Gemini Credit",
    "issuer": "Gemini",
    "type": "Credit",
    "network": "Mastercard",
    "cashbackMax": 4,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "US",
    "officialLink": "https://www.gemini.com/credit-card",
    "metal": true,
    "stakingRequired": "None",
    "atmLimit": "Cash Advance Fees",
    "mobilePay": true,
    "supportedAssets": "Rewards in 60+",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Earn up to 4% on every purchase",
      "Earn bitcoin, or 50+ cryptos available on Gemini",
      "Rewards are instantly deposited"
    ]
  },
  {
    "id": "metamask-card",
    "rank": 9,
    "name": "MetaMask Card",
    "issuer": "ConsenSys",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 3,
    "annualFee": "Free",
    "fxFee": "1% (Metal tier 0%)",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "EU, UK, US",
    "officialLink": "https://metamask.io/card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "No fee up to $1,200/mo, then 2%",
    "mobilePay": true,
    "supportedAssets": "USDC, USDT, ETH",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR",
      "GBP"
    ],
    "perks": [
      "Self-Custody",
      "Linea Network",
      "Direct Spending",
      "Earn 1 MetaMask Rewards point for every $1 USD you spend",
      "crypto cashback",
      "exclusive benefits from our global partner network"
    ]
  },
  {
    "id": "etherfi-card",
    "rank": 10,
    "name": "Ether.fi Cash",
    "issuer": "Ether.fi",
    "type": "Credit",
    "network": "Visa",
    "cashbackMax": 15,
    "annualFee": "Free",
    "fxFee": "1%",
    "signupBonus": "Points",
    "custody": "Non-Custodial",
    "regions": "US",
    "officialLink": "https://www.ether.fi/cash",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "2% fee",
    "mobilePay": true,
    "supportedAssets": "USDC (Yielding)",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "DeFi Native",
      "Yield Bearing",
      "Borrow vs ETH",
      "Cashback on every purchase",
      "Free physical cards",
      "Virtual cards",
      "Contactless payment",
      "Apple Pay & Google Pay",
      "Non-custodial account",
      "Use your crypto",
      "Spend with value-accruing stables",
      "Family Member Cards w/ controls (coming soon)",
      "Referral rewards (1% Cashback on referral purchases + 10% points on their deposits)",
      "Airport Companion lounge access",
      "Concierge",
      "Priority support (24/7 Live Chat and email)",
      "Crypto concierge (coming soon)",
      "Exclusive hotel discounts (Up to 65% off luxury hotels)",
      "Price protection Up to $2K",
      "Purchase protection Up to $10K",
      "Extended warranty Up to $10K",
      "Auto rental insurance"
    ]
  },
  {
    "id": "wirex-card",
    "rank": 11,
    "name": "Wirex Card",
    "issuer": "Wirex",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 8,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "1000 WXT",
    "custody": "Custodial",
    "regions": "Global (130+ countries)",
    "officialLink": "https://www.wirexapp.com/",
    "metal": false,
    "stakingRequired": "Yes (WXT)",
    "atmLimit": "$400/mo Free",
    "mobilePay": true,
    "supportedAssets": "150+ Cryptos",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR",
      "GBP",
      "SGD",
      "AUD",
      "HKD",
      "INR"
    ],
    "perks": [
      "Earn up to 8% Cryptoback™ on every purchase",
      "Fee-free ATM withdrawals worldwide"
    ]
  },
  {
    "id": "bitpay-card",
    "rank": 12,
    "name": "BitPay Card",
    "issuer": "BitPay",
    "type": "Prepaid",
    "network": "Mastercard",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "3%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "US",
    "officialLink": "https://www.bitpay.com/card",
    "status": "inactive",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.bitpay.com/",
    "availabilityNote": "Legacy BitPay prepaid card program appears discontinued; BitPay now emphasizes wallet, gift cards, bill pay, and merchant payments.",
    "cardForm": "Legacy",
    "cryptoRole": "Legacy/discontinued card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "$2,000/day",
    "mobilePay": true,
    "supportedAssets": "15+ Top Caps",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Instant Loading",
      "High Limits",
      "Secure"
    ]
  },
  {
    "id": "coca-card",
    "rank": 13,
    "name": "Coca Card",
    "issuer": "COCA",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 8,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "EEA, UK, Global",
    "officialLink": "https://www.coca.xyz/",
    "metal": false,
    "stakingRequired": "Yes (for Tiers)",
    "atmLimit": "$250/mo free",
    "mobilePay": true,
    "supportedAssets": "USDT, USDC, EURC, EURS (15+ chains)",
    "kyc": "Light",
    "supportedCurrencies": [
      "EUR",
      "USD",
      "GBP"
    ],
    "perks": [
      "MPC Wallet",
      "Non-Custodial",
      "Privacy Focus",
      "Up to 8% Cashback",
      "6% APY on balances",
      "50% off subscriptions"
    ]
  },
  {
    "id": "brighty-card",
    "rank": 14,
    "name": "Brighty Card",
    "issuer": "Brighty",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 1.75,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "EEA",
    "officialLink": "https://brighty.app/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€200/mo Free",
    "mobilePay": true,
    "supportedAssets": "USDT, EURT, USDC",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "USDT"
    ],
    "perks": [
      "Daily Interest",
      "Instant Exchange",
      "Digital Bank",
      "Up to 10% APY on crypto",
      "AI-Driven Wealth",
      "Seamless Transactions",
      "Quick Deposits"
    ]
  },
  {
    "id": "cypher-card",
    "rank": 15,
    "name": "Cypher Card",
    "issuer": "Cypher",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": "Variable",
    "annualFee": "$0 (Basic with Virtual Card), $199 (Premium)",
    "fxFee": "0.75%-1.75%",
    "signupBonus": "100 $CYPR with referral code",
    "custody": "Non-Custodial",
    "regions": "Global",
    "officialLink": "https://cypherhq.io/card",
    "metal": true,
    "stakingRequired": "None",
    "atmLimit": "$2,000/day",
    "mobilePay": true,
    "supportedAssets": "1000+ tokens across 15 chains",
    "kyc": "None",
    "supportedCurrencies": [
      "USD",
      "Global"
    ],
    "perks": [
      "Private Spending",
      "Luxury",
      "Concierge",
      "Instant off ramp from crypto to fiat",
      "Both physical and virtual card",
      "Superior card controls",
      "Load with any non-custodial wallet",
      "Family spending",
      "Fraud protection"
    ]
  },
  {
    "id": "venmo-card",
    "rank": 16,
    "name": "Venmo Credit",
    "issuer": "Venmo",
    "type": "Credit",
    "network": "Visa",
    "cashbackMax": 3,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "US",
    "officialLink": "https://venmo.com/about/creditcard",
    "status": "active",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://help.venmo.com/cs/articles/cash-back-to-crypto-for-the-venmo-credit-card-faq-vhel271",
    "availabilityNote": "Not direct crypto spending; cash back can be used to auto-buy crypto in Venmo.",
    "cardForm": "Physical + virtual",
    "cryptoRole": "Crypto rewards only",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "$400/day",
    "mobilePay": true,
    "supportedAssets": "BTC, ETH, LTC, BCH",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Auto-Purchase Crypto",
      "Split Purchases",
      "Social Feed"
    ]
  },
  {
    "id": "bitrefill-card",
    "rank": 17,
    "name": "Bitrefill Card",
    "issuer": "Bitrefill",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "-",
    "custody": "Custodial",
    "regions": "Europe",
    "officialLink": "https://www.bitrefill.com/card/?hl=en",
    "status": "verify",
    "statusCheckedAt": "2026-06-27",
    "evidenceUrl": "https://www.bitrefill.com/card/?hl=en",
    "availabilityNote": "Card page exists, but issuer terms and current regional availability need a closer check before treating as fully verified.",
    "cardForm": "Virtual + physical where available",
    "cryptoRole": "Crypto-funded prepaid card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€350/day & €3,000/month",
    "mobilePay": true,
    "supportedAssets": "USDC, BTC, ETH, BNB, Polygon, Solana",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "No monthly fee",
      "No issuing fee",
      "Virtual & Physical Card",
      "Unlimited SEPA Withdrawal Limit",
      "24/7 support",
      "Withdraw cash at ATMs globally"
    ]
  },
  {
    "id": "whitebit-card",
    "rank": 18,
    "name": "WhiteBIT Card",
    "issuer": "WhiteBIT",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 10,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "EEA",
    "officialLink": "https://whitebit.com/crypto-card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€2,500/mo",
    "mobilePay": true,
    "supportedAssets": "WBT, USDT, BTC, ETH, XRP, SOL, NEAR, ADA, AVAX, EUR, DOGE",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "USD",
      "UAH"
    ],
    "perks": [
      "WBIT Holder Perks",
      "Fast Verification",
      "Secure",
      "up to 10% cashback in BTC",
      "zero fees for top-up",
      "contactless payments",
      "earn cashback in selected categories",
      "referral program"
    ]
  },
  {
    "id": "wayex-card",
    "rank": 19,
    "name": "Wayex Card",
    "issuer": "Wayex",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 1,
    "annualFee": "Free",
    "fxFee": "0% on USD",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "US, Global",
    "officialLink": "https://www.wayex.com/en-US",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Not specified",
    "mobilePay": true,
    "supportedAssets": "Stablecoins (USDC, USDT)",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "EUR"
    ],
    "perks": [
      "Crypto to Fiat",
      "Instant",
      "User Friendly",
      "Automatic yield (up to 5% everyday, up to 20% fixed-term)",
      "instant swaps",
      "global USD/EUR accounts"
    ]
  },
  {
    "id": "gnosis-card",
    "rank": 20,
    "name": "Gnosis Pay",
    "issuer": "Gnosis",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 4,
    "annualFee": "€30",
    "fxFee": "Optional",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "UK, EEA",
    "officialLink": "https://gnosispay.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€500/day",
    "mobilePay": true,
    "supportedAssets": "EURe, GNO, ETH, USDC, EURC",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "GBP"
    ],
    "perks": [
      "On-chain",
      "Self-Custody",
      "Developer Friendly",
      "Instant Deployment",
      "Multi-Currency Native",
      "Self-Custodial",
      "Global Coverage"
    ]
  },
  {
    "id": "fold-card",
    "rank": 21,
    "name": "Fold Card",
    "issuer": "Fold",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 15,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "Free Sats",
    "custody": "Custodial",
    "regions": "US",
    "officialLink": "https://foldapp.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "No Fees (In-Network)",
    "mobilePay": true,
    "supportedAssets": "Bitcoin Only",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Bitcoin Rewards",
      "Spin Wheel",
      "Bill Pay",
      "Buy and sell bitcoin with zero fees",
      "Up to 1.5% back with ACH bill pay rewards",
      "Gift card rewards and up to 15% back on merchant boosts",
      "1.5% back on categories like dining and travel"
    ]
  },
  {
    "id": "bleap-card",
    "rank": 22,
    "name": "Bleap Card",
    "issuer": "Bleap",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 2,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "EEA",
    "officialLink": "https://www.bleap.finance/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€400/mo free",
    "mobilePay": true,
    "supportedAssets": "USDC, ETH",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR"
    ],
    "perks": [
      "Account Abstraction",
      "Gasless",
      "Easy Setup",
      "Instant crypto-to-fiat conversion",
      "free ATM withdrawals up to $400",
      "Apple Pay/Google Pay support"
    ]
  },
  {
    "id": "bitpanda-card",
    "rank": 23,
    "name": "Bitpanda Card",
    "issuer": "Bitpanda",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 1,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "None",
    "custody": "Custodial",
    "regions": "EEA",
    "officialLink": "https://www.bitpanda.com/en/card",
    "metal": false,
    "stakingRequired": "Yes (BEST)",
    "atmLimit": "€500/day",
    "mobilePay": true,
    "supportedAssets": "All Bitpanda Assets",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR"
    ],
    "perks": [
      "Spend Assets",
      "Metals",
      "Stocks",
      "Free card",
      "No monthly costs",
      "0% FX fees for non-Euro transactions",
      "In-app card management",
      "Apple Pay support",
      "Real-time spending tracking",
      "Visa security & fraud prevention"
    ]
  },
  {
    "id": "zypto-card",
    "rank": 24,
    "name": "Zypto Card",
    "issuer": "Zypto",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "2%",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "Global",
    "officialLink": "https://zypto.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Varies",
    "mobilePay": true,
    "supportedAssets": "100+ cryptocurrencies",
    "kyc": "Light",
    "supportedCurrencies": [
      "USD",
      "EUR",
      "Global"
    ],
    "perks": [
      "Virtual Cards",
      "Gift Cards",
      "Wide Crypto Support",
      "Use anywhere Visa is accepted",
      "Up to $1M in spending power",
      "Fast KYC",
      "Instant funding",
      "Premium VISA benefits",
      "Personal concierge",
      "Travel and lifestyle benefits"
    ]
  },
  {
    "id": "ledger-card",
    "rank": 25,
    "name": "Ledger CL",
    "issuer": "Ledger",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 1,
    "annualFee": "Free",
    "fxFee": "1%",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "UK, EEA",
    "officialLink": "https://shop.ledger.com/pages/cl-card-crypto-card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€600/mo",
    "mobilePay": true,
    "supportedAssets": "BTC, ETH, USDT",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "GBP",
      "USD"
    ],
    "perks": [
      "Ledger Live",
      "Secured by Ledger",
      "Collateral",
      "Earn 1% cashback crypto rewards",
      "Securely top up your card with crypto",
      "Withdraw cash at ATMs",
      "Unlock liquidity while holding onto your assets"
    ]
  },
  {
    "id": "tuyo-card",
    "rank": 26,
    "name": "Tuyo Card",
    "issuer": "Tuyo",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "up to 1% for non-USD",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "US, EEA, LATAM",
    "officialLink": "https://tuyo.com/card",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Not supported",
    "mobilePay": true,
    "supportedAssets": "USDC, USDT",
    "kyc": "None",
    "supportedCurrencies": [
      "USD",
      "EUR"
    ],
    "perks": [
      "Latin America",
      "Easy Onramp",
      "Mobile First",
      "Keeping custody (self-custodial)",
      "Privacy of transaction details",
      "Compatibility with USDC on Base",
      "Support for mobile wallets (Apple Pay and Google Pay)"
    ]
  },
  {
    "id": "redotpay-card",
    "rank": 27,
    "name": "RedotPay Card",
    "issuer": "RedotPay",
    "type": "Prepaid",
    "network": "Visa",
    "cashbackMax": 0,
    "annualFee": "Free",
    "fxFee": "1.2%",
    "signupBonus": "$5",
    "custody": "Custodial",
    "regions": "Global (excluding US/Sanctioned)",
    "officialLink": "https://www.redotpay.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "$500/day",
    "mobilePay": true,
    "supportedAssets": "USDT, USDC, BTC, ETH",
    "kyc": "Light",
    "supportedCurrencies": [
      "USD",
      "HKD",
      "Global"
    ],
    "perks": [
      "Hong Kong",
      "Virtual Card",
      "Fast KYC",
      "Shop, withdraw, and manage your funds globally",
      "No Annual Fees",
      "Simply tap or swipe to pay",
      "Withdraw cash at ATMs globally"
    ]
  },
  {
    "id": "tria-card",
    "rank": 28,
    "name": "Tria Card",
    "issuer": "Tria",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 5,
    "annualFee": "Free",
    "fxFee": "0.5%",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "Global",
    "officialLink": "https://www.tria.so/en",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "Standard",
    "mobilePay": true,
    "supportedAssets": "BTC, Sol, and other 1000+ coins",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD",
      "Global"
    ],
    "perks": [
      "Chain Abstraction",
      "Any Token",
      "Gasless",
      "Boosted Rewards with Tria Card",
      "Activate higher yields and exclusive opportunities when you hold and use a Tria Card"
    ]
  },
  {
    "id": "avici-card",
    "rank": 29,
    "name": "Avici Card",
    "issuer": "Avici",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 2,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "Waitlist",
    "custody": "Non-Custodial",
    "regions": "EEA",
    "officialLink": "https://avici.money/",
    "metal": true,
    "stakingRequired": "None",
    "atmLimit": "€1,000/day",
    "mobilePay": true,
    "supportedAssets": "ERC-20 Tokens",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR"
    ],
    "perks": [
      "DeFi Integration",
      "Yield",
      "Premium Design",
      "1.5%–2% cashback on eligible purchases",
      "Instant virtual & physical cards"
    ]
  },
  {
    "id": "oobit-card",
    "rank": 30,
    "name": "Oobit Card",
    "issuer": "Oobit",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 6,
    "annualFee": "Free",
    "fxFee": "1%",
    "signupBonus": "10 OBT",
    "custody": "Non-Custodial",
    "regions": "EEA, USA, South Africa, Brazil",
    "officialLink": "https://www.oobit.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€500/day",
    "mobilePay": true,
    "supportedAssets": "BTC, ETH, OBT, USDT",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "USD",
      "BRL"
    ],
    "perks": [
      "Tap to Pay",
      "Instant Convert",
      "Rewards",
      "A crypto card that lets you use USDT, Bitcoin, Ethereum as cash",
      "Spend instantly at millions of stores"
    ]
  },
  {
    "id": "plutus-card",
    "rank": 31,
    "name": "Plutus Card",
    "issuer": "Plutus",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 9,
    "annualFee": "Free",
    "fxFee": "0%",
    "signupBonus": "$10 PLU",
    "custody": "Non-Custodial",
    "regions": "UK, EEA",
    "officialLink": "https://www.plutus.it/",
    "metal": false,
    "stakingRequired": "Yes (PLU)",
    "atmLimit": "£500/day",
    "mobilePay": true,
    "supportedAssets": "PLU, ETH, BTC",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "GBP"
    ],
    "perks": [
      "Perks Selection",
      "Stacking",
      "Subscription",
      "Earn 3-9% in PLUS Rewards on card spending",
      "enjoy £10 in rewards back monthly at 50+ Perks"
    ]
  },
  {
    "id": "deblock-card",
    "rank": 32,
    "name": "Deblock Card",
    "issuer": "Deblock",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": 1,
    "annualFee": "Free standard plan",
    "fxFee": "0%",
    "signupBonus": "3 months Premium Plan",
    "custody": "Non-Custodial",
    "regions": "EEA",
    "officialLink": "https://deblock.com/f-cca",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "€30,000/monthly",
    "mobilePay": true,
    "supportedAssets": "BTC, ETH, USDT, USDC, SOL, BNB, PENGU, HYPE, TON, and hundreds more",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR"
    ],
    "perks": [
      "Europe",
      "Virtual Card",
      "Self Custodial",
      "MiCA licensed",
      "Fast KYC",
      "Deblock is: IBAN, cards, instant bank transfers, currency and Crypto exchanges... For free and with no bank charges!",
      "No Annual Fees",
      "Custom NFT branded cards",
      "Withdraw cash at ATMs globally"
    ]
  },
  {
    "id": "ready-lite",
    "rank": 33,
    "name": "Ready Lite",
    "issuer": "Ready",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": 0.5,
    "annualFee": "Free",
    "fxFee": "Zero FX fees",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "Global",
    "officialLink": "https://t.co/uXiZjnByAs",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "$200/month free",
    "mobilePay": true,
    "supportedAssets": "Bitcoin, ETH, USDC",
    "kyc": "Required",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "0.5% Cashback",
      "0% FX fees",
      "Virtual card",
      "Google Pay",
      "Apple Pay coming soon"
    ]
  },
  {
    "id": "tapx-card",
    "rank": 34,
    "name": "TapX Card",
    "issuer": "TapX",
    "type": "Debit",
    "network": "Visa/Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "0% FX fees",
    "signupBonus": "None",
    "custody": "Self-Custody",
    "regions": "Global",
    "officialLink": "https://tapxcard.com",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "Varies by plan",
    "mobilePay": true,
    "supportedAssets": "Bitcoin, USDT, 70+ cryptocurrencies",
    "kyc": "Light",
    "supportedCurrencies": [
      "USD"
    ],
    "perks": [
      "Cashback coming soon",
      "0% FX fees",
      "Physical & virtual card",
      "Google Pay",
      "Apple Pay"
    ]
  },
  {
    "id": "fiat24-card",
    "rank": 35,
    "name": "Fiat24 Card",
    "issuer": "Fiat24",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "Included in top-up fee (varies by tier)",
    "signupBonus": "None",
    "custody": "Hybrid",
    "regions": "Europe, Asia, Oceania, North America (specific countries with limits)",
    "officialLink": "https://fiat24.com/",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "N/A (virtual card)",
    "mobilePay": true,
    "supportedAssets": "ETH, USDC, USDC.e, USDT, ARB, LON, EUR24, CHF24, USD24, CNH24 (Arbitrum)",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD"
    ],
    "perks": [
      "dApp",
      "Swiss IBAN",
      "Multicurrency",
      "Tokenized fiat",
      "SEPA/SWIFT payments",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay"
    ]
  },
  {
    "id": "thorwallet-card",
    "rank": 36,
    "name": "THORWallet Card",
    "issuer": "THORWallet",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "1% (standard tier)",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "100+ countries (Europe, Asia, Oceania, North America)",
    "officialLink": "https://www.thorwallet.org/",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "$10,000/day (standard tier)",
    "mobilePay": true,
    "supportedAssets": "Over 20,000 crypto tokens including ETH, USDC, USDT, BTC",
    "kyc": "Required",
    "supportedCurrencies": [
      "CHF",
      "EUR",
      "USD",
      "RMB"
    ],
    "perks": [
      "Non-custodial",
      "Swiss IBAN account",
      "Multicurrency support (CHF, EUR, USD, RMB)",
      "Tokenized fiat",
      "No monthly fees",
      "Apple Pay",
      "Google Pay",
      "SEPA/SWIFT payments"
    ]
  },
  {
    "id": "safepal-card",
    "rank": 37,
    "name": "SafePal Card",
    "issuer": "SafePal",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "1%",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "60+ countries (Europe, Asia, Oceania, North America)",
    "officialLink": "https://www.safepal.com/en/bank",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "€5,000/day",
    "mobilePay": true,
    "supportedAssets": "Crypto across 40+ blockchains including ETH, USDC, USDT, BTC",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD"
    ],
    "perks": [
      "Non-custodial",
      "Swiss IBAN account",
      "Multicurrency",
      "Lowest fees",
      "Easy setup",
      "Referral commission up to 40%",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay",
      "SEPA/SWIFT payments"
    ]
  },
  {
    "id": "ur-card",
    "rank": 38,
    "name": "UR Card",
    "issuer": "UR",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "Europe, Asia, Oceania, North America",
    "officialLink": "https://ur.app/",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "$11,611/day",
    "mobilePay": true,
    "supportedAssets": "ETH, USDT, USDC, USDT0, WBTC, USDS, USDe, WETH, MNT, ENA, mETH, stETH, PYUSD, LINK, UNI, AAVE, LDO, PENDLE, ARB, POL, ENS, crvUSD, PAXG, XAUt; Fiat: EUR24, CHF24, USD24, CNH24, JPY24, SGD24, HKD24 (Arbitrum)",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD",
      "SGD",
      "HKD",
      "JPY"
    ],
    "perks": [
      "Neobank",
      "Swiss IBAN account",
      "Multicurrency",
      "Banking trust",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay",
      "SEPA/SWIFT payments"
    ]
  },
  {
    "id": "savepay-card",
    "rank": 39,
    "name": "SavePay Card",
    "issuer": "SavePay",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "Europe, Asia, Oceania, North America",
    "officialLink": "https://savepay.gitbook.io/savepay",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "$109,384.22/month",
    "mobilePay": true,
    "supportedAssets": "ETH, USDC, USDC.e, USDT, ARB, LON; Fiat: EUR24, CHF24, USD24, CNH24 (Arbitrum)",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD"
    ],
    "perks": [
      "Non-custodial",
      "Swiss IBAN",
      "Free card",
      "SEPA/SWIFT",
      "Ultra low fees",
      "Multicurrency",
      "Referral commission 60%",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay"
    ]
  },
  {
    "id": "imtoken-card",
    "rank": 40,
    "name": "imToken Card",
    "issuer": "imToken",
    "type": "Debit",
    "network": "Mastercard",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "Low",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "Europe, Asia, Oceania, North America",
    "officialLink": "https://token.im/card?locale=en-US",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "N/A (virtual card)",
    "mobilePay": true,
    "supportedAssets": "ETH, USDC, USDT, WBTC (Arbitrum/ERC-20); Fiat: EUR24, CHF24, USD24, CNH24",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD"
    ],
    "perks": [
      "Non-custodial",
      "Swiss IBAN",
      "SEPA/SWIFT",
      "Low fees",
      "Multicurrency",
      "High spend limits",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay"
    ]
  },
  {
    "id": "tokenpocket-card",
    "rank": 41,
    "name": "TokenPocket Card",
    "issuer": "TokenPocket",
    "type": "Debit",
    "network": "Visa",
    "cashbackMax": null,
    "annualFee": "Free",
    "fxFee": "Not specified",
    "signupBonus": "None",
    "custody": "Non-Custodial",
    "regions": "30+ countries (Europe, Asia, Oceania, North America)",
    "officialLink": "https://card.tokenpocket.pro/?locale=en",
    "metal": false,
    "stakingRequired": "No",
    "atmLimit": "$100,000/month",
    "mobilePay": true,
    "supportedAssets": "Any tokens on Arbitrum including ETH, USDC, USDT",
    "kyc": "Required",
    "supportedCurrencies": [
      "EUR",
      "CHF",
      "RMB",
      "USD"
    ],
    "perks": [
      "Non-custodial",
      "Swiss IBAN",
      "SEPA/SWIFT",
      "Low fees",
      "Multicurrency",
      "High spend limits",
      "Apple Pay",
      "Google Pay",
      "Samsung Pay",
      "Alipay",
      "WeChat Pay"
    ]
  },
  {
    "id": "bitgetwallet-card",
    "rank": 42,
    "name": "Bitget Wallet Card",
    "issuer": "Bitget Wallet",
    "type": "Prepaid",
    "network": "Visa/Mastercard",
    "cashbackMax": 2.2,
    "annualFee": "Free",
    "fxFee": "1.7%",
    "signupBonus": "$5",
    "custody": "Non-Custodial",
    "regions": "Global (Asia / LatAm / Europe, excluding US & sanctioned regions)",
    "officialLink": "https://web3.bitget.com/",
    "metal": false,
    "stakingRequired": "None",
    "atmLimit": "$10,000/day",
    "mobilePay": true,
    "supportedAssets": "USDT, USDC",
    "kyc": "Light",
    "supportedCurrencies": [
      "USD",
      "Global"
    ],
    "perks": [
      "0 Fees",
      "Google-rate FX",
      "0 Fees on everyday spending (within monthly limit)",
      "Spend crypto like cash, globally",
      "Virtual Card & Physical Card supported",
      "Apple Pay & Google Pay ready",
      "Accepted worldwide (Visa, Mastercard network)",
      "Fast & seamless KYC",
      "Custom card designs & brand collaborations"
    ]
  }
];
